### ISSUE TITLE
Not deleting travelnet path on explosion.

### ISSUE THREAD

**Issue by mootpoint** [FozLand/travelnet#2]
When tnt explodes a Travelnet, it leaves the station, but returns the travelnet. You can travel to the destination but not from it. It should be expected if travelnet no longer is there, then... delete that path.

**Comment by mootpoint** [comment]
I've taken a look and i believe this : on_blast = function() end will fix this problem. if you want ill add it to this and you can ask for it to be pulled upstream?

**Comment by jhcole** [comment]
After further review, it looks like this was already fixed upstream by Sokomine/travelnet@121f8f61f23d128cde497125bbbbfb1293b34b19. The upstream solution is to delete the path and then send the player back to the originating travelnet.

Regardless of the bug, do you think travelnets should be immune to tnt?

EDIT: This question also applies to elevators.

**Comment by mootpoint** [comment]
Yes, specifically have in mind the mining nets people place, I'd like to
encourage mining with tnt, but not at the risk of replacing those
travelnets every day or giving players free travelnets.  Talked to hd, he
is against tnt all together, but did say no one should be able to harm
others stuff. So I would say make them indestructible.
